type PermissionType =
  'resumo_pendentes_pagamento'
  | 'resumo_pendentes_recebimento'
  | 'resumo_cartao_credito'
  | 'fluxo_caixa'
  | 'debitos_compensados'
  | 'creditos_compensados'
  | 'indicadores_financeiros'
  | 'resumo_mensal_abastecimento'
  | 'resumo_patrimonio_abastecimento'
  | 'resumo_combustivel_abastecimento'
  | 'producao_produtividade'
  | 'descontos_producao'
  | 'custo_producao_categoria'
  | 'custo_producao_talhao'
  | 'custo_producao_insumo_atividade'
  | 'custo_producao_insumo_manutencao'
  | 'custo_producao_insumo_abastecimento'
  | 'contratos'
  | 'contratos_romaneios'
  | 'vendas_por_cliente'
  | 'vendas_preco_medio_por_cliente'
  | 'vendas_preco_medio_por_mes'

